import os

Import("main_env")
Import("libautosave")

objects = [main_env.Object("specs.cpp")]
for module in ["core"]:
    objects.extend(SConscript(
        os.path.join(module, "SConscript"),
        exports="main_env",
        ))

specs = main_env.Program(
    target = "specs",
    source = objects + [libautosave],
    )

run = main_env.Command(
    target="#run-tests",
    source = specs,
    action = "./$SOURCE",
    )

result = [specs, run]
Return("result")
