import os

Import("test_env")
Import("libautosave")

objects = [test_env.Object("specs.cpp")]
for module in ["core"]:
    objects.extend(SConscript(
        os.path.join(module, "SConscript"),
        exports="test_env",
        ))

specs = test_env.Program(
    target = "specs",
    source = objects + [libautosave],
    )

run = test_env.Command(
    target="#run-tests",
    source = specs,
    action = "./$SOURCE",
    )

result = [specs, run]
Return("result")
