#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDI_A                                   100
#define IDI_CONNECTEDFILE                       101
#define IDI_DISABLED                            102
#define IDM_ABOUT                               104
#define IDD_SETTINGS_MORE                       110
#define IDI_COUNT0                              110
#define IDD_SETTINGS_TARGET                     111
#define IDI_COUNT1                              111
#define IDD_SETTINGS_UNINSTALL                  112
#define IDI_COUNT2                              112
#define IDI_COUNT3                              113
#define IDI_COUNT4                              114
#define IDI_COUNT5                              115
#define IDI_OK                                  116
#define IDC_MENU                                136
#define IDD_UNINSTALL_INTRO                     139
#define IDD_UNINSTALL_AUTOSTART                 141
#define IDD_UNINSTALL_SHORTCUTS                 143
#define IDD_UNINSTALL_REGISTRY                  145
#define IDD_UNINSTALL_ERROR                     147
#define IDD_UNINSTALL_OUTRO                     149
#define IDD_SHORTCUTS                           152
#define IDD_ABOUT                               155
#define IDC_ABOUT_VERSION                       40000
#define IDC_AUTOSAVE                            40000
#define IDC_SETTINGS_CURWINEDIT                 40000
#define IDC_SETTINGS_HOTKEYEDIT                 40000
#define IDC_SHORTCUTS_RESULT                    40000
#define IDC_UNINSTALL_AUTOSTART                 40000
#define IDC_UNINSTALL_CONVERT                   40000
#define IDC_UNINSTALL_ERRORTEXT                 40000
#define IDM_OPTIONS                             40000
#define IDC_ABOUT_DATE                          40001
#define IDC_SETTINGS_FILTEREDIT                 40001
#define IDC_SETTINGS_INTERVALEDIT               40001
#define IDC_SHORTCUTS_SOURCE                    40001
#define IDC_UNINSTALL_CONNCUT                   40001
#define IDC_UNINSTALL_DELETE                    40001
#define IDM_NOOPTIONS                           40001
#define IDS_APP_TITLE                           40001
#define IDC_ABOUT_ICON                          40002
#define IDC_SETTINGS_INTERVALUPDOWN             40002
#define IDC_SETTINGS_WINDOWLIST                 40002
#define IDC_SHORTCUTS_CUSTOMCHECK               40002
#define IDC_UNINSTALL_ALL                       40002
#define IDC_UNINSTALL_FILELIST                  40002
#define IDM_ENABLE                              40002
#define IDS_STARTED_CAPTION                     40002
#define IDC_SETTINGS_ISREGEXCHECK               40003
#define IDC_SETTINGS_VERBOSITYLIST              40003
#define IDC_SHORTCUTS_HOTKEYEDIT                40003
#define IDC_UNINSTALL_REGISTRY                  40003
#define IDM_DISABLE                             40003
#define IDS_STARTED_TEXT                        40003
#define IDC_SETTINGS_CONNCUTBUTTON              40004
#define IDC_SHORTCUTS_HOTKEYCHECK               40004
#define IDM_CLOSE                               40004
#define IDS_DISABLED_CAPTION                    40004
#define IDC_SETTINGS_AUTOSTARTBUTTON            40005
#define IDC_SHORTCUTS_INTERVALEDIT              40005
#define IDS_DISABLED_TEXT                       40005
#define IDC_SETTINGS_ABOUT                      40006
#define IDC_SHORTCUTS_INTERVALUPDOWN            40006
#define IDS_ALERT_CAPTION                       40006
#define IDC_SHORTCUTS_INTERVALCHECK             40007
#define IDS_ALERT_TEXT                          40007
#define IDC_SHORTCUTS_VERBOSITYCHECK            40008
#define IDS_ERROR_NOTARGET                      40008
#define IDC_SHORTCUTS_VERBOSITYLIST             40009
#define IDS_ERROR_BADREGEX                      40009
#define IDC_SHORTCUTS_SHUTDOWNCHECK             40010
#define IDS_ERROR_NOHOTKEY                      40010
#define IDS_AUTOSTARTWARNING                    40011
#define IDS_VERBOSITY_DESC0                     40012
#define IDS_VERBOSITY_DESC1                     40013
#define IDS_VERBOSITY_DESC2                     40014
#define IDS_VERBOSITY_DESC3                     40015
#define IDS_SLV_EMPTYSOURCE                     40016
#define IDS_SLV_EMPTYRESULT                     40017
#define IDS_SLV_SOURCEERROR                     40018
#define IDS_SLV_RESULTERROR                     40019
#define IDS_SLV_WAIT                            40020
#define IDS_TARGET_EMPTY                        40021
#define IDS_TARGET_BADREGEX                     40022
#define IDS_TARGET_NOWINDOWS                    40023
#define IDS_ERROR_NODROPPEDSHORTCUTS            40024
