import os

Import("main_env")

main_object = main_env.Object("autosave.cpp")

other_objects = []
for module in ["core"]:
    other_objects.extend(SConscript(
        os.path.join(module, "SConscript"),
        exports="main_env",
        ))

libautosave = main_env.StaticLibrary(
    target = "autosave",
    source = other_objects,
    )

program = main_env.Program(
    target = "autosave",
    source = [main_object, libautosave],
    )

result = [libautosave, program]
Return("result")
